import { SidebarProvider } from "./SidebarContext";
import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "../components/admin/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="bg-[#f5f5f5] flex ">
        <Sidebar />
        <main className="w-full overflow-auto h-svh">{children}</main>
      </div>
    </SidebarProvider>
  );
}
